### ISSUE TITLE
Package neofetch has invalid Hash

### ISSUE THREAD

**Issue by Benji377** [AcaciaLinux/branch#64]
![image_2023-03-10_084751564](https://user-images.githubusercontent.com/50681275/224255016-6bd261e8-ef72-437c-bed7-cc179e0ea909.png)

When installing neofetch, it warns you about it having an invalid hash. It does let you install it, and it does seem to work when ignoring the warning.

**Comment by zimsneexh** [comment]
This issue may have been caused by an out-of-date leaf packagelist. Make sure to run `leaf update` before installing a package.
