### ISSUE TITLE
ModuleNotFoundError: No module named 'blog'

### ISSUE THREAD

**Issue by Benji377** [AcaciaLinux/branch#83]
**Describe the bug**
I am trying to set up BranchClient on Ubuntu WSL and keep encountering a strange Python-related bug. Specifically, I am following an old guide I somewhat wrote together while @zimsneexh showed me how to use the client. Here are the steps I followed:

**To Reproduce**
1. Clone the repository at the release tag with `git clone --depth 1 --branch v0.6 https://github.com/AcaciaLinux/branch.git`
2. `cd branch`
3. `sudo make`
4. `cd branchclient`
5. `sudo make`
6. Change the configuration file at `/etc/branch/client.conf` with my username and password
7. Execute `sudo sh branchclient`
8. Encounter the error:
```sh
Traceback (most recent call last):
  File "/opt/branch/client/src/main.py", line 20, in <module>
    import blog
ModuleNotFoundError: No module named 'blog'
```

**Expected behavior**
At first, I thought this might be a problem with python, but I noticed that I can install blog using the command `pip install blog` just fine. And even after installing it manually, the error persists. 

**Desktop (please complete the following information):**
 - OS: Windows with WSL2 Ubuntu

**Additional context**
Here is the output from the two make commands:
```sh
> benji@hpenvy:~/branch$ sudo make
Installing submodules...
make -C submodules branchlog
make[1]: Entering directory '/home/benji/branch/submodules'
make[1]: 'branchlog' is up to date.
make[1]: Leaving directory '/home/benji/branch/submodules'
Installing client...
make -C branchclient
make[1]: Entering directory '/home/benji/branch/branchclient'
Installing branchclient..
mkdir -p /opt/branch/client
cp -R src/ /opt/branch/client/
cp branchclient /usr/bin/
chmod +x /usr/bin/branchclient
Done!
make[1]: Leaving directory '/home/benji/branch/branchclient'
Installing buildbot...
make -C branchbuildbot
make[1]: Entering directory '/home/benji/branch/branchbuildbot'
Installing branchbuildbot..
mkdir -p /opt/branch/buildbot
cp -R src/ /opt/branch/buildbot/
cp branchbuildbot /usr/bin/
chmod +x /usr/bin/branchbuildbot
Done!
make[1]: Leaving directory '/home/benji/branch/branchbuildbot'
Installing master...
make -C branchmaster
make[1]: Entering directory '/home/benji/branch/branchmaster'
Installing branchmaster..
mkdir -p /opt/branch/master
cp -R src/ /opt/branch/master/
cp branchmaster /usr/bin/
chmod +x /usr/bin/branchmaster
Done!
make[1]: Leaving directory '/home/benji/branch/branchmaster'
> benji@hpenvy:~/branch$ cd branchclient/
> benji@hpenvy:~/branch/branchclient$ sudo make
Installing branchclient..
mkdir -p /opt/branch/client
cp -R src/ /opt/branch/client/
cp branchclient /usr/bin/
chmod +x /usr/bin/branchclient
Done!
```

**Comment by zimsneexh** [comment]
The issue you are facing is related to how `make` handles sub directories. Use `make -B install_submodules` to install all required submodules. Make sure to run this make command as the user you intend to run the client as, since every user has their own Python environment.

**Comment by Benji377** [comment]
Thank you, I see now this step was missing in my notes. Let me test this quickly, so we can close this issue as solved
